### ISSUE TITLE
Progress is slow

### ISSUE THREAD

**Issue by matthewwilson** [yokall/piboiler-pi#1]
Y U no commit?

**Comment by k-vaughan** [comment]
Intermittent networking issues.  You need to be able to connect to Github for more than 10 seconds to make a commit.

**Comment by matthewwilson** [comment]
Shocking @k-vaughan, you got your proxy set, as the old saying go's, its always the proxy, if not proxy then colin

**Comment by matthewwilson** [comment]
Also feel free to play the greatest game of all time while you wait - http://catastrophegame.herokuapp.com/

**Comment by matthewwilson** [comment]
Also feel free to use last years winning application to aid with inter team communication https://pingchatapp.herokuapp.com/

**Comment by matthewwilson** [comment]
@yokall any updates? please revert on high priority

**Comment by matthewwilson** [comment]
any updates?

**Comment by benpf-pes** [comment]
These project is in danger of growing stagnant

**Comment by matthewwilson** [comment]
agreed @benpf-pes, @yokall you busy or something?

**Comment by matthewwilson** [comment]
@yokall any updates?

**Comment by k-vaughan** [comment]
Dear @matthewcodes,

Thank you for your message. We always appreciate hearing from our fans.

After discussing the issue with our key stakeholders this project has been temporarily suspended. It's our hope that we can resume working on this piece of ground-breaking software at some undetermined time in the future but unfortunately, for now at least, we're going to have to put it on the ... back-burner.

Although this decision might be disappointing for you, our biggest fan, it's important to realise that sometimes this is a natural part of software development - sometimes other priorities arise and a tough decision has to be made to allocate resources elsewhere.

Please know that we do appreciate your continued support. You can expect great things from us in the future and I have no doubt that we'll continue to inspire you.

**Comment by matthewwilson** [comment]
@k-vaughan I could fork this repository and continue to develop it in your honour, but alas this is an empty repo, was this put on the back-burner from the get go?
